[application]

# App (Project) Name
name = "hot_dog"

[web.app]

# HTML title tag content
title = "HotDog!"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "com.digitalmccullough.hotdog"
publisher = "digitalmccullough.com"
icon = ["assets/icon.png"]
